name: Create resources using Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Check out Git Repository
        uses: actions/checkout@v3

      # Cache TFLint plugins directory
      - name: Cache plugin dir
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      # Print TFLint version
      - name: Show TFLint version
        run: tflint --version

      # Install TFLint plugins
      - name: Init TFLint
        run: tflint --init

      # Run TFLint
      - name: Run TFLint
        run: tflint -f compact --recursive --force

      # Run Tfsec
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      # Set up Python 3.8 for Checkov
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Test with Checkov
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./Terraform_code
          framework: terraform
